name: Frontend workflow

on:
  push:
    branches: register
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Run the tests
      run: npm test
    - name: Build the application
      run: npm run build